#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    tests-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-xhgui-80"
      tls: false
      # middlewares:
      #   - "tests-redirectHttps"
    tests-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-web-80"
      tls: false
      # middlewares:
      #   - "tests-redirectHttps"
    tests-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-web-8025"
      tls: false
      # middlewares:
      #   - "tests-redirectHttps"
    
    
    tests-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-xhgui-80"
      
      tls: true
      
    
    
    tests-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-web-80"
      
      tls: true
      
    tests-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^tests\.ddev\.site$`)
      
      service: "tests-web-8025"
      
      tls: true
      
    

  middlewares:
    tests-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    tests-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-tests-xhgui:80
        
    
    tests-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-tests-web:80
        
    tests-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-tests-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/tests.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/tests.key